import { Inter } from "next/font/google";
import "./globals.css";
import "antd/dist/reset.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { ConfigProvider, theme } from 'antd';
import Header from "./components/Header";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <ConfigProvider
          theme={{
            algorithm: theme.defaultAlgorithm,
            token: {
              colorPrimary: '#0070f3',
              colorBgBase: '#ffffff',
              colorTextBase: '#111827',
              borderRadius: 8,
            },
          }}
        >
          <Header />
          <main className="main-container">{children}</main>
        </ConfigProvider>
      </body>
    </html>
  );
}
