import { Inter } from "next/font/google";
import "./globals.css";
import "antd/dist/reset.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { ConfigProvider, theme } from 'antd';
import Header from "./components/Header";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <ConfigProvider
          theme={{
            algorithm: theme.darkAlgorithm,
            token: {
              colorPrimary: '#00f6ff',
              colorBgBase: '#0a0f1f',
              colorTextBase: '#d1d5db',
              borderRadius: 8,
            },
            components: {
              Card: {
                colorBgContainer: 'rgba(16, 22, 43, 0.8)',
                borderColor: 'rgba(0, 246, 255, 0.2)',
              },
              Input: {
                colorBgContainer: 'rgba(10, 15, 31, 0.8)',
                borderColor: 'rgba(0, 246, 255, 0.2)',
              },
              Select: {
                colorBgContainer: 'rgba(10, 15, 31, 0.8)',
              }
            }
          }}
        >
          <Header />
          <main className="main-container">{children}</main>
        </ConfigProvider>
      </body>
    </html>
  );
}
